### ISSUE TITLE
About the worldexpo_10

### ISSUE THREAD

**Issue by ZachZou-logs** [FDU-VTS/CVCode#1]
Thank you for your code, I have a question about the world_10.py. 
First, I have a difficulty about understanding the worldexo, in which has a folder called train_perspective but no information about the train_perspective in your code, what is train_perspective function? 
Second, what is your principle about the gaussian_filter_density of  world_10.py?
Looking forward to your reply！

**Comment by loukey** [comment]
> Thank you for your code, I have a question about the world_10.py.
> First, I have a difficulty about understanding the worldexo, in which has a folder called train_perspective but no information about the train_perspective in your code, what is train_perspective function?
> Second, what is your principle about the gaussian_filter_density of world_10.py?
> Looking forward to your reply！

Hi, train_perspective is like a mask for each image, because not all of the people have been annotationed. The sigma of world_10 is 15 refered from https://github.com/gjy3035/C-3-Framework and https://zhuanlan.zhihu.com/p/65650998. And we are developing an Pypi framework crowd-count in https://github.com/FDU-VTS/crowd-count. You may can get some help from that, and document will be released in few days. Thanks.

**Comment by ZachZou-logs** [comment]
Thank your reply and your links!  But I still have a question. As you have said, train_perspective has its function in crowd counting, why doesn't it appear in the document，and doesn't that make an error for our train and test?

**Comment by loukey** [comment]
> Thank your reply and your links! But I still have a question. As you have said, train_perspective has its function in crowd counting, why doesn't it appear in the document，and doesn't that make an error for our train and test?

Which document you mentioned? I have reviewed our code just now, we have `roi` function in line 235, and the world_10 is not a good dataset, so we have not continued to do researches with it. The codes aren't be maintained more than a year, maybe some problems still exsit.

**Comment by ZachZou-logs** [comment]
The document is world_10.py, and when I searched "perspective" in your repository, but I couldn't find any clues.The dataset has perspective and roi, they are different in the dataset.


 
---Original---

**Comment by loukey** [comment]
> The document is world_10.py, and when I searched "perspective" in your repository, but I couldn't find any clues.The dataset has perspective and roi, they seem&nbsp; different.
> […](#)
> ---Original--- From: "Songjian Chen"<notifications@github.com&gt; Date: Fri, Nov 29, 2019 16:23 PM To: "FDU-VTS/CVCode"<CVCode@noreply.github.com&gt;; Cc: "Author"<author@noreply.github.com&gt;;"Sharpshooter_one"<1422737852@qq.com&gt;; Subject: Re: [FDU-VTS/CVCode] About the worldexpo_10 (#1) Thank your reply and your links! But I still have a question. As you have said, train_perspective has its function in crowd counting, why doesn't it appear in the document，and doesn't that make an error for our train and test? Which document you mentioned? I have reviewed our code just now, we have roi function in line 235, and the world_10 is not a good dataset, so we have not continued to do researches with it. The codes aren't be maintained more than a year, maybe some problems still exsit. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Oh, sorry for my carelessness, the persfective is the adjustice for camera persfective distortions. `Different scenes have different perspective distortions, crowd distributions and lighting conditions. Without additional training data, the model trained in one specific scene has difficulty being used for other scenes. ` refered from the world_10 paper.  `The pixel value in the perspective map M(p) denotes that the number of pixels in the image representing one meter at that location` In this paper, they use adaptive kernel captured from persfective maps: `we set the variance σh = 0.2M(p) for the term Nh, and σx = 0.2M(p), σy = 0.5M(p) for the term N`(in section 3.1). And in section 4.1, `each input patch is normalized into the same scale, which covers a 3-meter by 3-meter square in the actual scene according to the perspective map`  they cropped the image in to 3m * 3m and then generate the density map. I think we just generated the density map with sigma 15 at that time and didn't add the codes of persfective maps. I'm so sorry.

**Comment by ZachZou-logs** [comment]
OK, thank you for your careful answer, I think the link will help you to add the codes of perspective map.
 [https://github.com/wk910930/crowd_density_segmentation](url)

And I have another question that how do you identify the wrong_data in the dataset(world_10.py)?

**Comment by loukey** [comment]
> OK, thank you for your careful answer, I think the link will help you to add the codes of perspective map.
> [https://github.com/wk910930/crowd_density_segmentation](url)
> 
> And I have another question that how do you identify the wrong_data in the dataset(world_10.py)?

ignore or re-annotate

**Comment by Sharpshooter-one** [comment]
yes ,this operation to wrong_data, but how do we determine the definition of wrong_data?

**Comment by ZachZou-logs** [comment]
> > OK, thank you for your careful answer, I think the link will help you to add the codes of perspective map.
> > [https://github.com/wk910930/crowd_density_segmentation](url)
> > And I have another question that how do you identify the wrong_data in the dataset(world_10.py)?
> 
> ignore or re-annotate
yes ,this operation to wrong_data, but how do we determine the definition of wrong_data

**Comment by loukey** [comment]
> > > OK, thank you for your careful answer, I think the link will help you to add the codes of perspective map.
> > > [https://github.com/wk910930/crowd_density_segmentation](url)
> > > And I have another question that how do you identify the wrong_data in the dataset(world_10.py)?
> > 
> > 
> > ignore or re-annotate
> > yes ,this operation to wrong_data, but how do we determine the definition of wrong_data

display the annotations and the images, and you can find the wrong data.

**Comment by Sharpshooter-one** [comment]
Okay! thank you very much!

**Comment by ZachZou-logs** [comment]
> > > > OK, thank you for your careful answer, I think the link will help you to add the codes of perspective map.
> > > > [https://github.com/wk910930/crowd_density_segmentation](url)
> > > > And I have another question that how do you identify the wrong_data in the dataset(world_10.py)?
> > > 
> > > 
> > > ignore or re-annotate
> > > yes ,this operation to wrong_data, but how do we determine the definition of wrong_data
> 
> display the annotations and the images, and you can find the wrong data.

Okay! thank you very much!

**Comment by chenwenhe11** [comment]
Hi, how did you get the WorldExpo'10 dataset? I sent an email to Prof. Xie Rong but never got a reply.
If possible, could you share the download link for the dataset with me, thank you very much!
My email is 476334028@qq.com.
